-- ============================================================
-- Phase 1: Machine & Mould History, Tool Life Tracking & TPM
-- IATF 16949 Clause 8.5.1.5 (Total Productive Maintenance)
-- ============================================================

-- 1. Extend machines table with technical specifications
ALTER TABLE machines ADD COLUMN IF NOT EXISTS tonnage INTEGER DEFAULT 100;
ALTER TABLE machines ADD COLUMN IF NOT EXISTS make_model TEXT DEFAULT 'Injection Moulding Machine';
ALTER TABLE machines ADD COLUMN IF NOT EXISTS year_of_commission INTEGER DEFAULT 2020;
ALTER TABLE machines ADD COLUMN IF NOT EXISTS screw_diameter_mm NUMERIC DEFAULT 35;
ALTER TABLE machines ADD COLUMN IF NOT EXISTS clamping_force_kn NUMERIC DEFAULT 1000;
ALTER TABLE machines ADD COLUMN IF NOT EXISTS pm_due_date DATE DEFAULT (CURRENT_DATE + INTERVAL '30 days');

-- Update machine tonnages with realistic plant specs matching SHRP 10 machines
UPDATE machines SET tonnage = 80,  make_model = 'L&T Demag Ergotech 80', year_of_commission = 2018, clamping_force_kn = 800 WHERE machine_code = 'HSIM - 01';
UPDATE machines SET tonnage = 100, make_model = 'L&T Demag Ergotech 100', year_of_commission = 2019, clamping_force_kn = 1000 WHERE machine_code = 'HSIM - 02';
UPDATE machines SET tonnage = 100, make_model = 'Toshiba EC100SX Electric', year_of_commission = 2021, clamping_force_kn = 1000 WHERE machine_code = 'HSIM - 03';
UPDATE machines SET tonnage = 120, make_model = 'Toshiba EC120SX Electric', year_of_commission = 2022, clamping_force_kn = 1200 WHERE machine_code = 'HSIM - 04';
UPDATE machines SET tonnage = 150, make_model = 'Ferromatik Milacron Magna T150', year_of_commission = 2017, clamping_force_kn = 1500 WHERE machine_code = 'HSIM - 05';
UPDATE machines SET tonnage = 80,  make_model = 'Vertical Servo Moulding VSIM-80', year_of_commission = 2020, clamping_force_kn = 800 WHERE machine_code = 'VSIM - 01';
UPDATE machines SET tonnage = 50,  make_model = 'Vertical Injection Moulding VIM-50', year_of_commission = 2015, clamping_force_kn = 500 WHERE machine_code = 'VIM - 01';
UPDATE machines SET tonnage = 60,  make_model = 'Vertical Injection Moulding VIM-60', year_of_commission = 2016, clamping_force_kn = 600 WHERE machine_code = 'VIM - 02';
UPDATE machines SET tonnage = 60,  make_model = 'Vertical Injection Moulding VIM-60', year_of_commission = 2016, clamping_force_kn = 600 WHERE machine_code = 'VIM - 03';
UPDATE machines SET tonnage = 100, make_model = 'Rubber Compression Moulding Press', year_of_commission = 2014, clamping_force_kn = 1000 WHERE machine_code = 'RUB - 01';

-- 2. Mould Master & Shot Life Tracking
CREATE TABLE IF NOT EXISTS moulds (
  id SERIAL PRIMARY KEY,
  mould_code TEXT UNIQUE NOT NULL,
  mould_name TEXT NOT NULL,
  ownership TEXT DEFAULT 'SHRP' CHECK (ownership IN ('SHRP', 'Customer')),
  customer_name TEXT,
  total_cavities INTEGER DEFAULT 1,
  active_cavities INTEGER DEFAULT 1,
  cumulative_shots INTEGER DEFAULT 0,
  shots_since_pm INTEGER DEFAULT 0,
  pm_interval_shots INTEGER DEFAULT 20000,
  storage_location TEXT DEFAULT 'Tool Crib Rack A-01',
  status TEXT DEFAULT 'ready' CHECK (status IN ('ready', 'running', 'under_maintenance', 'damaged')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Mould to Part Linkage
CREATE TABLE IF NOT EXISTS mould_parts (
  id SERIAL PRIMARY KEY,
  mould_id INTEGER NOT NULL REFERENCES moulds(id) ON DELETE CASCADE,
  part_id INTEGER NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  cavities_for_part INTEGER DEFAULT 1,
  UNIQUE (mould_id, part_id)
);

CREATE INDEX IF NOT EXISTS idx_mould_parts_part ON mould_parts(part_id);
CREATE INDEX IF NOT EXISTS idx_mould_parts_mould ON mould_parts(mould_id);

-- 4. Mould Maintenance & PM Audit Log
CREATE TABLE IF NOT EXISTS mould_maintenance_logs (
  id SERIAL PRIMARY KEY,
  mould_id INTEGER NOT NULL REFERENCES moulds(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL CHECK (action_type IN ('pm_service', 'repair', 'inspection', 'polishing', 'overhaul')),
  shots_at_service INTEGER NOT NULL,
  description TEXT NOT NULL,
  technician_name TEXT NOT NULL,
  logged_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mould_maint_mould ON mould_maintenance_logs(mould_id, created_at DESC);

-- 5. Machine Breakdown & TPM Log
CREATE TABLE IF NOT EXISTS machine_breakdown_logs (
  id SERIAL PRIMARY KEY,
  machine_id INTEGER NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  incident_date DATE NOT NULL DEFAULT CURRENT_DATE,
  breakdown_type TEXT NOT NULL CHECK (breakdown_type IN ('hydraulic', 'electrical', 'mechanical', 'heater', 'pneumatic', 'other')),
  downtime_minutes INTEGER NOT NULL DEFAULT 0,
  root_cause TEXT,
  corrective_action TEXT,
  parts_replaced TEXT,
  technician_name TEXT,
  logged_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_machine_bd_machine ON machine_breakdown_logs(machine_id, incident_date DESC);

-- Authentic Mould Master from FORM ENTRY 26-271.xlsm
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC01', 'A710 (A710BBWBA 01)', 'Customer', 'HASI CHENNAI', 6, 6, 4270, 4270, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC01' AND (p.shrp_part_code = 'A710' OR p.part_name = 'A710BBWBA 01' OR p.customer_part_no = 'A710BBWBA 01' OR p.part_code = 'A710BBWBA 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC02', 'F364 (F364-CB5AA-01)', 'Customer', 'HASI CHENNAI', 16, 16, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 16 FROM moulds m, parts p WHERE m.mould_code = 'SH HC02' AND (p.shrp_part_code = 'F364' OR p.part_name = 'F364-CB5AA-01' OR p.customer_part_no = 'F364-CB5AA-01' OR p.part_code = 'F364-CB5AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC03', 'F364 GS (F364-CB5AA-01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01, 02, 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC03' AND (p.shrp_part_code = 'F364 GS' OR p.part_name = 'F364-CB5AA-01' OR p.customer_part_no = 'F364-CB5AA-01' OR p.part_code = 'F364-CB5AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC04', 'F442 KQ (F442-KQAAA-01)', 'Customer', 'HASI CHENNAI', 6, 6, 675, 675, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC04' AND (p.shrp_part_code = 'F442 KQ' OR p.part_name = 'F442-KQAAA-01' OR p.customer_part_no = 'F442-KQAAA-01' OR p.part_code = 'F442-KQAAA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC05', 'F442 QQ (F442-QQ7AA-01)', 'Customer', 'HASI CHENNAI', 4, 4, 920, 920, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC05' AND (p.shrp_part_code = 'F442 QQ' OR p.part_name = 'F442-QQ7AA-01' OR p.customer_part_no = 'F442-QQ7AA-01' OR p.part_code = 'F442-QQ7AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC06', 'F442 WB (F442-WBAAA-01)', 'Customer', 'HASI CHENNAI', 2, 2, 1059, 1059, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 2 FROM moulds m, parts p WHERE m.mould_code = 'SH HC06' AND (p.shrp_part_code = 'F442 WB' OR p.part_name = 'F442-WBAAA-01' OR p.customer_part_no = 'F442-WBAAA-01' OR p.part_code = 'F442-WBAAA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC07', 'F710 (F710-AKYAA-01)', 'Customer', 'HASI CHENNAI', 7, 7, 417, 417, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 7 FROM moulds m, parts p WHERE m.mould_code = 'SH HC07' AND (p.shrp_part_code = 'F710' OR p.part_name = 'F710-AKYAA-01' OR p.customer_part_no = 'F710-AKYAA-01' OR p.part_code = 'F710-AKYAA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC08', 'F885 Y (F885-BB1AA-01)', 'Customer', 'HASI CHENNAI', 6, 6, 3307, 3307, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC08' AND (p.shrp_part_code = 'F885 Y' OR p.part_name = 'F885-BB1AA-01' OR p.customer_part_no = 'F885-BB1AA-01' OR p.part_code = 'F885-BB1AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC09', 'AN6B (FC1F2AN6BA 01)', 'Customer', 'HASI CHENNAI', 4, 4, 10319, 10319, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC09' AND (p.shrp_part_code = 'AN6B' OR p.part_name = 'FC1F2AN6BA 01' OR p.customer_part_no = 'FC1F2AN6BA 01' OR p.part_code = 'FC1F2AN6BA 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC10', 'AA02 Y (FC1F2SPHAA 02)', 'Customer', 'HASI CHENNAI', 4, 4, 9550, 9550, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC10' AND (p.shrp_part_code = 'AA02 Y' OR p.part_name = 'FC1F2SPHAA 02' OR p.customer_part_no = 'FC1F2SPHAA 02' OR p.part_code = 'FC1F2SPHAA 02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC11', 'SULLA B (FC1F2SULLA 01)', 'Customer', 'HASI CHENNAI', 4, 4, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02 - SM50') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC11' AND (p.shrp_part_code = 'SULLA B' OR p.part_name = 'FC1F2SULLA 01' OR p.customer_part_no = 'FC1F2SULLA 01' OR p.part_code = 'FC1F2SULLA 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC12', 'UGKCA (FC1F2UGKCA 01)', 'Customer', 'HASI CHENNAI', 8, 8, 955, 955, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02 - SM50') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 8 FROM moulds m, parts p WHERE m.mould_code = 'SH HC12' AND (p.shrp_part_code = 'UGKCA' OR p.part_name = 'FC1F2UGKCA 01' OR p.customer_part_no = 'FC1F2UGKCA 01' OR p.part_code = 'FC1F2UGKCA 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC13', 'UMEAB (FC1F2UMEAB01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02 - SM50') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC13' AND (p.shrp_part_code = 'UMEAB' OR p.part_name = 'FC1F2UMEAB01' OR p.customer_part_no = 'FC1F2UMEAB01' OR p.part_code = 'FC1F2UMEAB01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC14', 'W501 (HA715L5G1A01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02, 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC14' AND (p.shrp_part_code = 'W501' OR p.part_name = 'HA715L5G1A01' OR p.customer_part_no = 'HA715L5G1A01' OR p.part_code = 'HA715L5G1A01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC15', 'CXGAA (HC442CXGAA 01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC15' AND (p.shrp_part_code = 'CXGAA' OR p.part_name = 'HC442CXGAA 01' OR p.customer_part_no = 'HC442CXGAA 01' OR p.part_code = 'HC442CXGAA 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC16', 'AA03 (HC442SPHAA 03)', 'Customer', 'HASI CHENNAI', 4, 4, 5224, 5224, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC16' AND (p.shrp_part_code = 'AA03' OR p.part_name = 'HC442SPHAA 03' OR p.customer_part_no = 'HC442SPHAA 03' OR p.part_code = 'HC442SPHAA 03') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC17', 'SULAC (HC442SULAC01)', 'Customer', 'HASI CHENNAI', 4, 4, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC17' AND (p.shrp_part_code = 'SULAC' OR p.part_name = 'HC442SULAC01' OR p.customer_part_no = 'HC442SULAC01' OR p.part_code = 'HC442SULAC01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC18', 'QQVBA W (HC443QQVBA02)', 'Customer', 'HASI CHENNAI', 5, 5, 1676, 1676, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02, VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 5 FROM moulds m, parts p WHERE m.mould_code = 'SH HC18' AND (p.shrp_part_code = 'QQVBA W' OR p.part_name = 'HC443QQVBA02' OR p.customer_part_no = 'HC443QQVBA02' OR p.part_code = 'HC443QQVBA02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC19', 'JLR CAP (HL180F4W1A 01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC19' AND (p.shrp_part_code = 'JLR CAP' OR p.part_name = 'HL180F4W1A 01' OR p.customer_part_no = 'HL180F4W1A 01' OR p.part_code = 'HL180F4W1A 01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC20', 'DH7AA (HR230DH7AA01)', 'Customer', 'HASI CHENNAI', 4, 4, 1720, 1720, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC20' AND (p.shrp_part_code = 'DH7AA' OR p.part_name = 'HR230DH7AA01' OR p.customer_part_no = 'HR230DH7AA01' OR p.part_code = 'HR230DH7AA01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC21', 'PDPKA (HR230PDPKA02)', 'Customer', 'HASI CHENNAI', 4, 4, 1907, 1907, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC21' AND (p.shrp_part_code = 'PDPKA' OR p.part_name = 'HR230PDPKA02' OR p.customer_part_no = 'HR230PDPKA02' OR p.part_code = 'HR230PDPKA02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC22', 'VW DIA 16 - HW773A (HW773G9E1A01)', 'Customer', 'HASI CHENNAI', 6, 6, 7213, 7213, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC22' AND (p.shrp_part_code = 'VW DIA 16 - HW773A' OR p.part_name = 'HW773G9E1A01' OR p.customer_part_no = 'HW773G9E1A01' OR p.part_code = 'HW773G9E1A01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC23', 'VW DIA 8 - HW773B (HW773G9E1B01)', 'Customer', 'HASI CHENNAI', 6, 6, 13846, 13846, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC23' AND (p.shrp_part_code = 'VW DIA 8 - HW773B' OR p.part_name = 'HW773G9E1B01' OR p.customer_part_no = 'HW773G9E1B01' OR p.part_code = 'HW773G9E1B01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC24', 'NCBA (R230-NC5BA-01)', 'Customer', 'HASI CHENNAI', 4, 4, 6370, 6370, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02,03,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC24' AND (p.shrp_part_code = 'NCBA' OR p.part_name = 'R230-NC5BA-01' OR p.customer_part_no = 'R230-NC5BA-01' OR p.part_code = 'R230-NC5BA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC25', 'NCBB (R230-NC5BB-01)', 'Customer', 'HASI CHENNAI', 4, 4, 5090, 5090, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC25' AND (p.shrp_part_code = 'NCBB' OR p.part_name = 'R230-NC5BB-01' OR p.customer_part_no = 'R230-NC5BB-01' OR p.part_code = 'R230-NC5BB-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC26', '1901 (V0LC-01C019-01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC26' AND (p.shrp_part_code = '1901' OR p.part_name = 'V0LC-01C019-01' OR p.customer_part_no = 'V0LC-01C019-01' OR p.part_code = 'V0LC-01C019-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC27', '2100 (V0LC-01C021-00)', 'Customer', 'HASI CHENNAI', 6, 6, 3250, 3250, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC27' AND (p.shrp_part_code = '2100' OR p.part_name = 'V0LC-01C021-00' OR p.customer_part_no = 'V0LC-01C021-00' OR p.part_code = 'V0LC-01C021-00') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC28', '2200 (V0LC-01C022-00)', 'Customer', 'HASI CHENNAI', 6, 6, 13079, 13079, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01, VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC28' AND (p.shrp_part_code = '2200' OR p.part_name = 'V0LC-01C022-00' OR p.customer_part_no = 'V0LC-01C022-00' OR p.part_code = 'V0LC-01C022-00') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC29', '2800 (V0LC-01C028-00)', 'Customer', 'HASI CHENNAI', 4, 4, 3583, 3583, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01, VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC29' AND (p.shrp_part_code = '2800' OR p.part_name = 'V0LC-01C028-00' OR p.customer_part_no = 'V0LC-01C028-00' OR p.part_code = 'V0LC-01C028-00') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC30', 'VPAA (VP5N1H-407721-AA)', 'Customer', 'HASI CHENNAI', 6, 6, 5242, 5242, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02, 03,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC30' AND (p.shrp_part_code = 'VPAA' OR p.part_name = 'VP5N1H-407721-AA' OR p.customer_part_no = 'VP5N1H-407721-AA' OR p.part_code = 'VP5N1H-407721-AA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC31', 'VPFA (VP5N1H-407721-FA)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 01,02,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC31' AND (p.shrp_part_code = 'VPFA' OR p.part_name = 'VP5N1H-407721-FA' OR p.customer_part_no = 'VP5N1H-407721-FA' OR p.part_code = 'VP5N1H-407721-FA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC32', 'DM1C (DM1C4UBH1B01)', 'Customer', 'HASI CHENNAI', 8, 8, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: TPE-A85 | Suitable: HSIM 03, 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 8 FROM moulds m, parts p WHERE m.mould_code = 'SH HC32' AND (p.shrp_part_code = 'DM1C' OR p.part_name = 'DM1C4UBH1B01' OR p.customer_part_no = 'DM1C4UBH1B01' OR p.part_code = 'DM1C4UBH1B01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC33', 'LBB (HC442L3LBB01)', 'Customer', 'HASI CHENNAI', 4, 4, 4088, 4088, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC33' AND (p.shrp_part_code = 'LBB' OR p.part_name = 'HC442L3LBB01' OR p.customer_part_no = 'HC442L3LBB01' OR p.part_code = 'HC442L3LBB01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC34', 'LBC (HC442L3LBC02)', 'Customer', 'HASI CHENNAI', 4, 4, 2113, 2113, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC34' AND (p.shrp_part_code = 'LBC' OR p.part_name = 'HC442L3LBC02' OR p.customer_part_no = 'HC442L3LBC02' OR p.part_code = 'HC442L3LBC02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HP01', 'PUNE B (FC1E1BAE1D01)', 'Customer', 'HASI PUNE', 6, 6, 6370, 6370, 20000, 'Tool Crib Rack A-01', 'Raw Material: PPCP | Suitable: HSIM 03, 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HP01' AND (p.shrp_part_code = 'PUNE B' OR p.part_name = 'FC1E1BAE1D01' OR p.customer_part_no = 'FC1E1BAE1D01' OR p.part_code = 'FC1E1BAE1D01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HP02', 'PUNE S (HR241BAE1B01)', 'Customer', 'HASI PUNE', 6, 6, 6743, 6743, 20000, 'Tool Crib Rack A-01', 'Raw Material: PPCP | Suitable: HSIM 03, 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HP02' AND (p.shrp_part_code = 'PUNE S' OR p.part_name = 'HR241BAE1B01' OR p.customer_part_no = 'HR241BAE1B01' OR p.part_code = 'HR241BAE1B01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB01', 'BH-DIA 16 - MAA (FC1D4K5MAA)', 'Customer', 'HCCSIL BHIWADI', 6, 6, 8820, 8820, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 05, 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HB01' AND (p.shrp_part_code = 'BH-DIA 16 - MAA' OR p.part_name = 'FC1D4K5MAA' OR p.customer_part_no = 'FC1D4K5MAA' OR p.part_code = 'FC1D4K5MAA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB02', 'BH-DIA 12 -MBA (FC1E4K5MBA)', 'Customer', 'HCCSIL BHIWADI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 05, 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HB02' AND (p.shrp_part_code = 'BH-DIA 12 -MBA' OR p.part_name = 'FC1E4K5MBA' OR p.customer_part_no = 'FC1E4K5MBA' OR p.part_code = 'FC1E4K5MBA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB03', 'BH-DIA 8 (FC1P4L1E1A01)', 'Customer', 'HCCSIL BHIWADI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HB03' AND (p.shrp_part_code = 'BH-DIA 8' OR p.part_name = 'FC1P4L1E1A01' OR p.customer_part_no = 'FC1P4L1E1A01' OR p.part_code = 'FC1P4L1E1A01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB04', 'OUTLET/INLET (HC442G6C1B01/A01)', 'Customer', 'HCCSIL BHIWADI', 4, 4, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM-02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HB04' AND (p.shrp_part_code = 'OUTLET/INLET' OR p.part_name = 'HC442G6C1B01/A01' OR p.customer_part_no = 'HC442G6C1B01/A01' OR p.part_code = 'HC442G6C1B01/A01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB05', 'HR241 (HR241G6C1A01)', 'Customer', 'HCCSIL BHIWADI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02, 03, 05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HB05' AND (p.shrp_part_code = 'HR241' OR p.part_name = 'HR241G6C1A01' OR p.customer_part_no = 'HR241G6C1A01' OR p.part_code = 'HR241G6C1A01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB06', '9AA (R101WC9AA01)', 'Customer', 'HCCSIL BHIWADI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HB06' AND (p.shrp_part_code = '9AA' OR p.part_name = 'R101WC9AA01' OR p.customer_part_no = 'R101WC9AA01' OR p.part_code = 'R101WC9AA01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB07', 'R101 (VPR230-WC9AA-01)', 'Customer', 'HCCSIL BHIWADI', 4, 4, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HB07' AND (p.shrp_part_code = 'R101' OR p.part_name = 'VPR230-WC9AA-01' OR p.customer_part_no = 'VPR230-WC9AA-01' OR p.part_code = 'VPR230-WC9AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HB08', '9AB (VPR230-WC9AB-01)', 'Customer', 'HCCSIL BHIWADI', 4, 4, 1815, 1815, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HB08' AND (p.shrp_part_code = '9AB' OR p.part_name = 'VPR230-WC9AB-01' OR p.customer_part_no = 'VPR230-WC9AB-01' OR p.part_code = 'VPR230-WC9AB-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN01', 'F390 (F390-QQDC-A02)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN01' AND (p.shrp_part_code = 'F390' OR p.part_name = 'F390-QQDC-A02' OR p.customer_part_no = 'F390-QQDC-A02' OR p.part_code = 'F390-QQDC-A02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN02', 'KQ NEW (F442-KQ)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN02' AND (p.shrp_part_code = 'KQ NEW' OR p.part_name = 'F442-KQ' OR p.customer_part_no = 'F442-KQ' OR p.part_code = 'F442-KQ') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN03', 'SHRP-T7 (SHRP-T7)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN03' AND (p.shrp_part_code = 'SHRP-T7' OR p.part_name = 'SHRP-T7' OR p.customer_part_no = 'SHRP-T7' OR p.part_code = 'SHRP-T7') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN04', 'SHRP-T8 (SHRP-T8)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN04' AND (p.shrp_part_code = 'SHRP-T8' OR p.part_name = 'SHRP-T8' OR p.customer_part_no = 'SHRP-T8' OR p.part_code = 'SHRP-T8') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN05', 'DA (WC-SCP-ECC21-DA01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN05' AND (p.shrp_part_code = 'DA' OR p.part_name = 'WC-SCP-ECC21-DA01' OR p.customer_part_no = 'WC-SCP-ECC21-DA01' OR p.part_code = 'WC-SCP-ECC21-DA01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN06', 'LMF (WC-SCP-ECC21-LMF01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN06' AND (p.shrp_part_code = 'LMF' OR p.part_name = 'WC-SCP-ECC21-LMF01' OR p.customer_part_no = 'WC-SCP-ECC21-LMF01' OR p.part_code = 'WC-SCP-ECC21-LMF01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN07', 'LMM (WC-SCP-ECC21-LMM01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN07' AND (p.shrp_part_code = 'LMM' OR p.part_name = 'WC-SCP-ECC21-LMM01' OR p.customer_part_no = 'WC-SCP-ECC21-LMM01' OR p.part_code = 'WC-SCP-ECC21-LMM01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN08', 'SMF (WC-SCP-ECC21-SMF01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN08' AND (p.shrp_part_code = 'SMF' OR p.part_name = 'WC-SCP-ECC21-SMF01' OR p.customer_part_no = 'WC-SCP-ECC21-SMF01' OR p.part_code = 'WC-SCP-ECC21-SMF01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN09', 'SMM (WC-SCP-ECC21-SMM01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN09' AND (p.shrp_part_code = 'SMM' OR p.part_name = 'WC-SCP-ECC21-SMM01' OR p.customer_part_no = 'WC-SCP-ECC21-SMM01' OR p.part_code = 'WC-SCP-ECC21-SMM01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN10', 'NADB (WC-SCP-SC21NA-DB-01)', 'Customer', 'WONJIN', 1, 1, 755, 755, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM - 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN10' AND (p.shrp_part_code = 'NADB' OR p.part_name = 'WC-SCP-SC21NA-DB-01' OR p.customer_part_no = 'WC-SCP-SC21NA-DB-01' OR p.part_code = 'WC-SCP-SC21NA-DB-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN11', 'NALC (WC-SCP-SC21NA-LC-01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM - 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN11' AND (p.shrp_part_code = 'NALC' OR p.part_name = 'WC-SCP-SC21NA-LC-01' OR p.customer_part_no = 'WC-SCP-SC21NA-LC-01' OR p.part_code = 'WC-SCP-SC21NA-LC-01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH WN12', 'NATB (WC-SCP-SC21NA-TB-T01)', 'Customer', 'WONJIN', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VIM - 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH WN12' AND (p.shrp_part_code = 'NATB' OR p.part_name = 'WC-SCP-SC21NA-TB-T01' OR p.customer_part_no = 'WC-SCP-SC21NA-TB-T01' OR p.part_code = 'WC-SCP-SC21NA-TB-T01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH SC01', 'VP6T (VP6TLU-11N087-AA)', 'Customer', 'SONA COMSTAR', 1, 1, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: N.RUB | Suitable: RUB-01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 1 FROM moulds m, parts p WHERE m.mould_code = 'SH SC01' AND (p.shrp_part_code = 'VP6T' OR p.part_name = 'VP6TLU-11N087-AA' OR p.customer_part_no = 'VP6TLU-11N087-AA' OR p.part_code = 'VP6TLU-11N087-AA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC35', 'LAC BLUE (HC442L3LAC01)', 'Customer', 'HASI CHENNAI', 16, 16, 5742, 5742, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 03') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 16 FROM moulds m, parts p WHERE m.mould_code = 'SH HC35' AND (p.shrp_part_code = 'LAC BLUE' OR p.part_name = 'HC442L3LAC01' OR p.customer_part_no = 'HC442L3LAC01' OR p.part_code = 'HC442L3LAC01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC36', 'CAP ASY-SUC (CA581CAWXX01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: CA581 BIG | Suitable: RUB-01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC36' AND (p.shrp_part_code = 'CAP ASY-SUC' OR p.part_name = 'CA581CAWXX01' OR p.customer_part_no = 'CA581CAWXX01' OR p.part_code = 'CA581CAWXX01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC37', 'CAP ASY-DIS (CA582DDRXX01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: CA582 SMALL | Suitable: RUB-01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC37' AND (p.shrp_part_code = 'CAP ASY-DIS' OR p.part_name = 'CA582DDRXX01' OR p.customer_part_no = 'CA582DDRXX01' OR p.part_code = 'CA582DDRXX01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC38', 'OERAA (HC442OERAA01)', 'Customer', 'HASI CHENNAI', 6, 6, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC38' AND (p.shrp_part_code = 'OERAA' OR p.part_name = 'HC442OERAA01' OR p.customer_part_no = 'HC442OERAA01' OR p.part_code = 'HC442OERAA01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC39', 'QVEAC (HC442QVEAC)', 'Customer', 'HASI CHENNAI', 8, 8, 2100, 2100, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 8 FROM moulds m, parts p WHERE m.mould_code = 'SH HC39' AND (p.shrp_part_code = 'QVEAC' OR p.part_name = 'HC442QVEAC' OR p.customer_part_no = 'HC442QVEAC' OR p.part_code = 'HC442QVEAC') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC40', 'QVEBC (HC442QVEBC)', 'Customer', 'HASI CHENNAI', 8, 8, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 8 FROM moulds m, parts p WHERE m.mould_code = 'SH HC40' AND (p.shrp_part_code = 'QVEBC' OR p.part_name = 'HC442QVEBC' OR p.customer_part_no = 'HC442QVEBC' OR p.part_code = 'HC442QVEBC') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC41', 'FC1F2SPHCA01', 'Customer', 'HASI CHENNAI', 8, 8, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 8 FROM moulds m, parts p WHERE m.mould_code = 'SH HC41' AND (p.shrp_part_code = '' OR p.part_name = 'FC1F2SPHCA01' OR p.customer_part_no = 'FC1F2SPHCA01' OR p.part_code = 'FC1F2SPHCA01') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC42', 'UMEAA (FC1F2UMEAA)', 'Customer', 'HASI CHENNAI', 4, 4, 724, 724, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH HC42' AND (p.shrp_part_code = 'UMEAA' OR p.part_name = 'FC1F2UMEAA' OR p.customer_part_no = 'FC1F2UMEAA' OR p.part_code = 'FC1F2UMEAA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC43', 'UMNAA (FC1F2UMNAA)', 'Customer', 'HASI CHENNAI', 6, 6, 845, 845, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC43' AND (p.shrp_part_code = 'UMNAA' OR p.part_name = 'FC1F2UMNAA' OR p.customer_part_no = 'FC1F2UMNAA' OR p.part_code = 'FC1F2UMNAA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC44', 'NDGAA (FC1F2NDGAA)', 'Customer', 'HASI CHENNAI', 6, 6, 906, 906, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: HSIM 02') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC44' AND (p.shrp_part_code = 'NDGAA' OR p.part_name = 'FC1F2NDGAA' OR p.customer_part_no = 'FC1F2NDGAA' OR p.part_code = 'FC1F2NDGAA') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH HC01', 'CEEAA-ORANGE (FC1F2CEEAA02)', 'Customer', 'HASI CHENNAI', 6, 6, 1486, 1486, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE- ORANGE | Suitable: HSIM 04,05') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 6 FROM moulds m, parts p WHERE m.mould_code = 'SH HC01' AND (p.shrp_part_code = 'CEEAA-ORANGE' OR p.part_name = 'FC1F2CEEAA02' OR p.customer_part_no = 'FC1F2CEEAA02' OR p.part_code = 'FC1F2CEEAA02') ON CONFLICT (mould_id, part_id) DO NOTHING;
INSERT INTO moulds (mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities, cumulative_shots, shots_since_pm, pm_interval_shots, storage_location, notes) VALUES ('SH OLD01', 'F442 QQ (F442-QQ7AA-01)', 'Customer', 'HASI CHENNAI', 4, 4, 0, 0, 20000, 'Tool Crib Rack A-01', 'Raw Material: LDPE | Suitable: VSIM 01') ON CONFLICT (mould_code) DO UPDATE SET total_cavities = EXCLUDED.total_cavities, customer_name = EXCLUDED.customer_name, notes = EXCLUDED.notes;
INSERT INTO mould_parts (mould_id, part_id, cavities_for_part) SELECT m.id, p.id, 4 FROM moulds m, parts p WHERE m.mould_code = 'SH OLD01' AND (p.shrp_part_code = 'F442 QQ' OR p.part_name = 'F442-QQ7AA-01' OR p.customer_part_no = 'F442-QQ7AA-01' OR p.part_code = 'F442-QQ7AA-01') ON CONFLICT (mould_id, part_id) DO NOTHING;


-- 6. Sample historical maintenance & breakdown records for TPM tracking demonstration
INSERT INTO machine_breakdown_logs (machine_id, incident_date, breakdown_type, downtime_minutes, root_cause, corrective_action, parts_replaced, technician_name)
SELECT m.id, CURRENT_DATE - INTERVAL '12 days', 'heater', 45, 'Band heater burn out on Zone 2', 'Replaced ceramic band heater and verified thermocouple calibration', 'Zone 2 Band Heater 230V 1.5kW', 'MUTHUPANDI'
FROM machines m WHERE m.machine_code = 'HSIM - 01'
ON CONFLICT DO NOTHING;

INSERT INTO machine_breakdown_logs (machine_id, incident_date, breakdown_type, downtime_minutes, root_cause, corrective_action, parts_replaced, technician_name)
SELECT m.id, CURRENT_DATE - INTERVAL '5 days', 'hydraulic', 90, 'Hydraulic oil return line filter clogged', 'Flushed return line and replaced 10-micron element', 'Hydraulic Filter Cartridge', 'SAKTHIVEL'
FROM machines m WHERE m.machine_code = 'HSIM - 04'
ON CONFLICT DO NOTHING;

INSERT INTO mould_maintenance_logs (mould_id, action_type, shots_at_service, description, technician_name)
SELECT m.id, 'pm_service', 20000, 'Scheduled 20K PM: Core/cavity ultrasonic cleaning, guide pin greasing, vent deepening and parting line inspection.', 'MUTHUPANDI'
FROM moulds m WHERE m.mould_code = 'SH HC09'
ON CONFLICT DO NOTHING;
