-- Bulk operator/supervisor/admin accounts from the shop-floor master list.
-- All PINs are '1111' (bcrypt hash below) - operators should change these
-- via Change PIN after first login. Safe to re-run: existing usernames and
-- page-access rows are left untouched (ON CONFLICT DO NOTHING), so this only
-- adds accounts/pages that don't already exist.

INSERT INTO users (username, pin_hash, full_name, role) VALUES
  ('ambika', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'AMBIKA', 'operator'),
  ('priya', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'BANU PRIYA', 'operator'),
  ('bharath', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'BHARATH', 'operator'),
  ('bibrath', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'BIBRATH', 'operator'),
  ('bijoy', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'BIJOY', 'operator'),
  ('dhatchayani', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'DHATCHAYANI', 'operator'),
  ('jaganath', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'JAGANATH BISWAL', 'operator'),
  ('jiban', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'JIBAN', 'operator'),
  ('jitan', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'JITAN BISWAL', 'operator'),
  ('mathi', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'MATHI', 'operator'),
  ('mohan', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'MOHANRAJ', 'operator'),
  ('muthu', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'MUTHUPANDI', 'supervisor'),
  ('pandiyan', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'PANDIYAN', 'supervisor'),
  ('parameshwar', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'PARAMESHWAR', 'operator'),
  ('reethu', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'REETHU', 'operator'),
  ('sakthivel', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SAKTHIVEL', 'admin'),
  ('shanthi', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SHANTHI', 'operator'),
  ('soni', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SONI DEVI', 'operator'),
  ('subhankar', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SUBHANKAR BISWAL', 'operator'),
  ('subrath', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SUBRATH', 'operator'),
  ('sujatha', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'SUJATHA', 'operator'),
  ('thilaka', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'THILAKA', 'operator'),
  ('vidhya', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'VIDHYA', 'admin'),
  ('vijaya', '$2b$10$O/y.2iypRxkJQWgwFfsGt.BT.IIidKClGwkvIXaAbI3nyI9mR0c2G', 'VIJAYA', 'operator')
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_page_access (user_id, page_key)
SELECT u.id, v.page_key FROM users u
JOIN (VALUES
  ('ambika', 'entry'),
  ('ambika', 'log'),
  ('priya', 'trimming'),
  ('priya', 'log'),
  ('bharath', 'inspection'),
  ('bharath', 'packing'),
  ('bharath', 'log'),
  ('bibrath', 'inspection'),
  ('bibrath', 'packing'),
  ('bibrath', 'log'),
  ('bijoy', 'entry'),
  ('bijoy', 'log'),
  ('dhatchayani', 'entry'),
  ('dhatchayani', 'log'),
  ('jaganath', 'inspection'),
  ('jaganath', 'packing'),
  ('jaganath', 'log'),
  ('jiban', 'entry'),
  ('jiban', 'log'),
  ('jitan', 'entry'),
  ('jitan', 'log'),
  ('mathi', 'trimming'),
  ('mathi', 'log'),
  ('mohan', 'entry'),
  ('mohan', 'log'),
  ('muthu', 'mould_setup'),
  ('muthu', 'entry'),
  ('muthu', 'bag_entry'),
  ('muthu', 'trimming'),
  ('muthu', 'inspection'),
  ('muthu', 'packing'),
  ('muthu', 'log'),
  ('muthu', 'approvals'),
  ('muthu', 'parts'),
  ('pandiyan', 'mould_setup'),
  ('pandiyan', 'entry'),
  ('pandiyan', 'bag_entry'),
  ('pandiyan', 'trimming'),
  ('pandiyan', 'inspection'),
  ('pandiyan', 'packing'),
  ('pandiyan', 'log'),
  ('pandiyan', 'approvals'),
  ('pandiyan', 'parts'),
  ('parameshwar', 'entry'),
  ('parameshwar', 'log'),
  ('reethu', 'trimming'),
  ('reethu', 'log'),
  ('sakthivel', 'mould_setup'),
  ('sakthivel', 'entry'),
  ('sakthivel', 'bag_entry'),
  ('sakthivel', 'trimming'),
  ('sakthivel', 'inspection'),
  ('sakthivel', 'packing'),
  ('sakthivel', 'log'),
  ('sakthivel', 'approvals'),
  ('sakthivel', 'parts'),
  ('sakthivel', 'users'),
  ('shanthi', 'log'),
  ('soni', 'trimming'),
  ('soni', 'log'),
  ('subhankar', 'entry'),
  ('subhankar', 'log'),
  ('subrath', 'inspection'),
  ('subrath', 'packing'),
  ('subrath', 'log'),
  ('sujatha', 'entry'),
  ('sujatha', 'log'),
  ('thilaka', 'entry'),
  ('thilaka', 'log'),
  ('vidhya', 'mould_setup'),
  ('vidhya', 'entry'),
  ('vidhya', 'bag_entry'),
  ('vidhya', 'trimming'),
  ('vidhya', 'inspection'),
  ('vidhya', 'packing'),
  ('vidhya', 'log'),
  ('vidhya', 'approvals'),
  ('vidhya', 'parts'),
  ('vidhya', 'users'),
  ('vijaya', 'entry'),
  ('vijaya', 'log')
) AS v(username, page_key) ON v.username = u.username
WHERE u.deleted_at IS NULL AND u.active = TRUE
ON CONFLICT (user_id, page_key) DO NOTHING;
