const pool = require('./pool');

// Clean mapping of all 69 tooling masters from Erp Master Requirements.xlsx Mould Details:
const EXCEL_MOULDS = [
  {
    "mould_code": "SH HC01",
    "mould_name": "SH HC01 - A710",
    "shrp_part_name": "A710",
    "part_no": "A710-BBWBA-01",
    "cavities": 6,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC02",
    "mould_name": "SH HC02 - F364 16C",
    "shrp_part_name": "F364 16C",
    "part_no": "F364-CB5AA-01",
    "cavities": 16,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 01, HSIM - 04, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC03",
    "mould_name": "SH HC03 - F364 GS",
    "shrp_part_name": "F364 GS",
    "part_no": "F364-CB5AA-01",
    "cavities": 6,
    "yom": 2020,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 01, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC04",
    "mould_name": "SH HC04 - F442 KQ",
    "shrp_part_name": "F442 KQ",
    "part_no": "F442-KQAAA-01",
    "cavities": 6,
    "yom": 2011,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC05",
    "mould_name": "SH HC05 - F442 QQ",
    "shrp_part_name": "F442 QQ",
    "part_no": "F442-QQ7AA-01",
    "cavities": 4,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC06",
    "mould_name": "SH HC06 - F442 WB",
    "shrp_part_name": "F442 WB",
    "part_no": "F442-WBAAA-01",
    "cavities": 1,
    "yom": 2011,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VIM 03",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC07",
    "mould_name": "SH HC07 - F710",
    "shrp_part_name": "F710",
    "part_no": "F710-AKYAA-01",
    "cavities": 7,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 03, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC08",
    "mould_name": "SH HC08 - F885 Y",
    "shrp_part_name": "F885 Y",
    "part_no": "F885-BB1AA-01",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "HSIM - 01, HSIM - 02",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC09",
    "mould_name": "SH HC09 - AN6B",
    "shrp_part_name": "AN6B",
    "part_no": "FC1F2AN6BA 01",
    "cavities": 4,
    "yom": 2019,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 03, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC10",
    "mould_name": "SH HC10 - AA02 Y",
    "shrp_part_name": "AA02 Y",
    "part_no": "FC1F2SPHAA 02",
    "cavities": 4,
    "yom": 2019,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 01, HSIM - 02",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC11",
    "mould_name": "SH HC11 - SULLA",
    "shrp_part_name": "SULLA",
    "part_no": "FC1F2SULLA 01",
    "cavities": 4,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC12",
    "mould_name": "SH HC12 - UGKCA",
    "shrp_part_name": "UGKCA",
    "part_no": "FC1F2UGKCA 01",
    "cavities": 8,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE TOOL",
    "gate_type": "PIN GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC13",
    "mould_name": "SH HC13 - UMEAB",
    "shrp_part_name": "UMEAB",
    "part_no": "FC1F2UMEAB01",
    "cavities": 6,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC14",
    "mould_name": "SH HC14 - HA715",
    "shrp_part_name": "HA715",
    "part_no": "HA715L5G1A01",
    "cavities": 6,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03, HSIM - 04",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC15",
    "mould_name": "SH HC15 - CXGAA",
    "shrp_part_name": "CXGAA",
    "part_no": "HC442CXGAA 01",
    "cavities": 6,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC16",
    "mould_name": "SH HC16 - AA03",
    "shrp_part_name": "AA03",
    "part_no": "HC442SPHAA 03",
    "cavities": 4,
    "yom": 2019,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "HP TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC17",
    "mould_name": "SH HC17 - SULAC",
    "shrp_part_name": "SULAC",
    "part_no": "HC442SULAC01",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC18",
    "mould_name": "SH HC18 - QQVBA W",
    "shrp_part_name": "QQVBA W",
    "part_no": "HC443QQVBA02",
    "cavities": 5,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "HP TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC19",
    "mould_name": "SH HC19 - HL180",
    "shrp_part_name": "HL180",
    "part_no": "HL180F4W1A 01",
    "cavities": 4,
    "yom": 2020,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 02, VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC20",
    "mould_name": "SH HC20 - DH7AA",
    "shrp_part_name": "DH7AA",
    "part_no": "HR230DH7AA01",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC21",
    "mould_name": "SH HC21 - PDPKA",
    "shrp_part_name": "PDPKA",
    "part_no": "HR230PDPKA02",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC22",
    "mould_name": "SH HC22 - VW DIA 16 - HW773A",
    "shrp_part_name": "VW DIA 16 - HW773A",
    "part_no": "HW773G9E1A01",
    "cavities": 6,
    "yom": 2022,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC23",
    "mould_name": "SH HC23 - VW DIA 8 - HW773B",
    "shrp_part_name": "VW DIA 8 - HW773B",
    "part_no": "HW773G9E1B01",
    "cavities": 6,
    "yom": 2022,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC24",
    "mould_name": "SH HC24 - NCBA",
    "shrp_part_name": "NCBA",
    "part_no": "R230-NC5BA-01",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 03, HSIM - 04, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC25",
    "mould_name": "SH HC25 - NCBB",
    "shrp_part_name": "NCBB",
    "part_no": "R230-NC5BB-01",
    "cavities": 4,
    "yom": 2024,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC26",
    "mould_name": "SH HC26 - 1901",
    "shrp_part_name": "1901",
    "part_no": "V0LC-01C019-01",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC27",
    "mould_name": "SH HC27 - 2100",
    "shrp_part_name": "2100",
    "part_no": "V0LC-01C021-00",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC28",
    "mould_name": "SH HC28 - 2200",
    "shrp_part_name": "2200",
    "part_no": "V0LC-01C022-00",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC29",
    "mould_name": "SH HC29 - 2800",
    "shrp_part_name": "2800",
    "part_no": "V0LC-01C028-00",
    "cavities": 4,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "HSIM - 05, VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC30",
    "mould_name": "SH HC30 - VPAA",
    "shrp_part_name": "VPAA",
    "part_no": "VP5N1H-407721-AA",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 01, HSIM - 02, HSIM - 04",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC31",
    "mould_name": "SH HC31 - VPFA",
    "shrp_part_name": "VPFA",
    "part_no": "VP5N1H-407721-FA",
    "cavities": 6,
    "yom": 2007,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC32",
    "mould_name": "SH HC32 - DM1C",
    "shrp_part_name": "DM1C",
    "part_no": "DM1C4UBH1B01",
    "cavities": 8,
    "yom": 2023,
    "raw_material": "TPE MULTIFLEX",
    "mould_type": "3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03, HSIM - 05",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC33",
    "mould_name": "SH HC33 - LBB",
    "shrp_part_name": "LBB",
    "part_no": "HC442L3LBB01",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC34",
    "mould_name": "SH HC34 - LBC",
    "shrp_part_name": "LBC",
    "part_no": "HC442L3LBC02",
    "cavities": 4,
    "yom": 2023,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC35",
    "mould_name": "SH HC35 - LAC BLUE",
    "shrp_part_name": "LAC BLUE",
    "part_no": "HC442L3LAC01",
    "cavities": 16,
    "yom": 2024,
    "raw_material": "PVC GR65",
    "mould_type": "3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC36",
    "mould_name": "SH HC36 - AFM BIG",
    "shrp_part_name": "AFM BIG",
    "part_no": "CA581CAWXX01",
    "cavities": 6,
    "yom": 2024,
    "raw_material": "HNBR",
    "mould_type": "",
    "gate_type": "",
    "tool_maker": "AMMAN ENGINEERING",
    "suitable_machines": "RUB - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC37",
    "mould_name": "SH HC37 - AFM SMALL",
    "shrp_part_name": "AFM SMALL",
    "part_no": "CA582DDRXX01",
    "cavities": 6,
    "yom": 2024,
    "raw_material": "HNBR",
    "mould_type": "",
    "gate_type": "",
    "tool_maker": "AMMAN ENGINEERING",
    "suitable_machines": "RUB - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC38",
    "mould_name": "SH HC38 - OERAA",
    "shrp_part_name": "OERAA",
    "part_no": "HC442OERAA01",
    "cavities": 6,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VSIM - 01",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC39",
    "mould_name": "SH HC39 - QVEAC",
    "shrp_part_name": "QVEAC",
    "part_no": "HC442QVEAC",
    "cavities": 8,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 04",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC40",
    "mould_name": "SH HC40 - QVEBC",
    "shrp_part_name": "QVEBC",
    "part_no": "HC442QVEBC",
    "cavities": 8,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC41",
    "mould_name": "SH HC41 - SPHCA",
    "shrp_part_name": "SPHCA",
    "part_no": "FC1F2SPHCA01",
    "cavities": 8,
    "yom": 2025,
    "raw_material": "",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC42",
    "mould_name": "SH HC42 - UMEAA",
    "shrp_part_name": "UMEAA",
    "part_no": "FC1F2UMEAA",
    "cavities": 4,
    "yom": 2026,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC43",
    "mould_name": "SH HC43 - UMNAA",
    "shrp_part_name": "UMNAA",
    "part_no": "FC1F2UMNAA",
    "cavities": 6,
    "yom": 2026,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC44",
    "mould_name": "SH HC44 - NDGAA",
    "shrp_part_name": "NDGAA",
    "part_no": "FC1F2NDGAA",
    "cavities": 6,
    "yom": 2026,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HP01",
    "mould_name": "SH HP01 - PUNE B",
    "shrp_part_name": "PUNE B",
    "part_no": "FC1E1BAE1D01",
    "cavities": 6,
    "yom": 2020,
    "raw_material": "PPCP B030MG",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "SUBMERSIBLE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03",
    "ownership": "Customer",
    "customer_name": "HASI PUNE",
    "rack_no": ""
  },
  {
    "mould_code": "SH HP02",
    "mould_name": "SH HP02 - PUNE S",
    "shrp_part_name": "PUNE S",
    "part_no": "HR241BAE1B01",
    "cavities": 6,
    "yom": 2020,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "SUBMERSIBLE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HASI PUNE",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB01",
    "mould_name": "SH HB01 - BH-DIA 16",
    "shrp_part_name": "BH-DIA 16",
    "part_no": "PLFC1E4K5MAA-00",
    "cavities": 6,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 04, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB02",
    "mould_name": "SH HB02 - BH-DIA 12",
    "shrp_part_name": "BH-DIA 12",
    "part_no": "PLFC1E4K5MBA-00",
    "cavities": 6,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 02, HSIM - 03, HSIM - 04, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB03",
    "mould_name": "SH HB03 - BH-DIA 8",
    "shrp_part_name": "BH-DIA 8",
    "part_no": "FC1P4L1E1A01",
    "cavities": 6,
    "yom": 2021,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 04, HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB04",
    "mould_name": "SH HB04 - OUTLET/INLET",
    "shrp_part_name": "OUTLET/INLET",
    "part_no": "HC442G6C1B01/A01",
    "cavities": 4,
    "yom": 2018,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM-02",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB05",
    "mould_name": "SH HB05 - HR241",
    "shrp_part_name": "HR241",
    "part_no": "HR241G6C1A01",
    "cavities": 6,
    "yom": 2018,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 03",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB06",
    "mould_name": "SH HB06 - 9AA",
    "shrp_part_name": "9AA",
    "part_no": "R101WC9AA01",
    "cavities": 4,
    "yom": 2015,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM 02",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB07",
    "mould_name": "SH HB07 - R101",
    "shrp_part_name": "R101",
    "part_no": "VPR230-WC9AA-01",
    "cavities": 4,
    "yom": 2015,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "SUBMERSIBLE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM 02",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH HB08",
    "mould_name": "SH HB08 - 9AB",
    "shrp_part_name": "9AB",
    "part_no": "VPR230-WC9AB-01",
    "cavities": 4,
    "yom": 2015,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "SUBMERSIBLE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM 02",
    "ownership": "Customer",
    "customer_name": "HCCSIL BHIWADI",
    "rack_no": ""
  },
  {
    "mould_code": "SH SC01",
    "mould_name": "SH SC01 - VP6T",
    "shrp_part_name": "VP6T",
    "part_no": "VP6TLU-11N087-AA",
    "cavities": 16,
    "yom": null,
    "raw_material": "NBR",
    "mould_type": "",
    "gate_type": "",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "RUB-01",
    "ownership": "SHRP",
    "customer_name": "SONA COMSTAR",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN05",
    "mould_name": "SH WN05 - DA",
    "shrp_part_name": "DA",
    "part_no": "WC-SCP-ECC21-DA01",
    "cavities": 2,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 03",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN06",
    "mould_name": "SH WN06 - LMF",
    "shrp_part_name": "LMF",
    "part_no": "WC-SCP-ECC21-LMF01",
    "cavities": 2,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 03",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN07",
    "mould_name": "SH WN07 - LMM",
    "shrp_part_name": "LMM",
    "part_no": "WC-SCP-ECC21-LMM01",
    "cavities": 2,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 03",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN08",
    "mould_name": "SH WN08 - SMF",
    "shrp_part_name": "SMF",
    "part_no": "WC-SCP-ECC21-SMF01",
    "cavities": 2,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 03",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN09",
    "mould_name": "SH WN09 - SMM",
    "shrp_part_name": "SMM",
    "part_no": "WC-SCP-ECC21-SMM01",
    "cavities": 6,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 03",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN10",
    "mould_name": "SH WN10 - NADB",
    "shrp_part_name": "NADB",
    "part_no": "WC-SCP-SC21NA-DB-01",
    "cavities": 4,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "MM MOULDS",
    "suitable_machines": "VIM - 02",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN11",
    "mould_name": "SH WN11 - NALC",
    "shrp_part_name": "NALC",
    "part_no": "WC-SCP-SC21NA-LC-01",
    "cavities": 4,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "MM MOULDS",
    "suitable_machines": "VIM - 02",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN12",
    "mould_name": "SH WN12 - NATB",
    "shrp_part_name": "NATB",
    "part_no": "WC-SCP-SC21NA-TB-T01",
    "cavities": 4,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "MM MOULDS",
    "suitable_machines": "VIM - 02",
    "ownership": "Customer",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH WN13",
    "mould_name": "SH WN13 - ATBAB",
    "shrp_part_name": "ATBAB",
    "part_no": "F442-ATBAB-02",
    "cavities": 2,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM - 02",
    "ownership": "SHRP",
    "customer_name": "WONJIN",
    "rack_no": ""
  },
  {
    "mould_code": "SH HC01",
    "mould_name": "SH HC01 - CEEAA-ORANGE",
    "shrp_part_name": "CEEAA-ORANGE",
    "part_no": "FC1F2CEEAA02",
    "cavities": 6,
    "yom": 2025,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE - 3 PLATE TOOL",
    "gate_type": "PIN POINT GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "HSIM - 05",
    "ownership": "Customer",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH OLD01",
    "mould_name": "SH OLD01 - F442 QQ",
    "shrp_part_name": "F442 QQ",
    "part_no": "F442-QQ7AA-01",
    "cavities": 4,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "OLD",
    "suitable_machines": "VSIM - 01",
    "ownership": "SHRP",
    "customer_name": "HASI CHENNAI",
    "rack_no": ""
  },
  {
    "mould_code": "SH AR01",
    "mould_name": "SH AR01 - Handle",
    "shrp_part_name": "Handle",
    "part_no": "HandlePlastic",
    "cavities": 1,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM-03",
    "ownership": "SHRP",
    "customer_name": "AVADH RAIL",
    "rack_no": ""
  },
  {
    "mould_code": "SH PL01",
    "mould_name": "SH PL01 - Syrnge Cap",
    "shrp_part_name": "Syrnge Cap",
    "part_no": "SYRNGECAP",
    "cavities": 12,
    "yom": null,
    "raw_material": "TPE MULTIFLEX",
    "mould_type": "2 PLATE TOOL",
    "gate_type": "EDGE GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM-03",
    "ownership": "Customer",
    "customer_name": "PRECISE LAPPING",
    "rack_no": ""
  },
  {
    "mould_code": "SH VK01",
    "mould_name": "SH VK01 - Small Grommet",
    "shrp_part_name": "Small Grommet",
    "part_no": "SmallGrommet",
    "cavities": 4,
    "yom": null,
    "raw_material": "LDPE 16MA400",
    "mould_type": "SIDE CORE TOOL",
    "gate_type": "PIN GATE",
    "tool_maker": "JJ TOOLS",
    "suitable_machines": "VIM-02",
    "ownership": "Customer",
    "customer_name": "VK INDUSTRIES",
    "rack_no": ""
  }
];

async function syncMoulds(closePool = false) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    for (const m of EXCEL_MOULDS) {
      const existing = await client.query(
        'SELECT id FROM moulds WHERE mould_code = $1 LIMIT 1',
        [m.mould_code]
      );

      let mouldId;
      if (existing.rows.length > 0) {
        mouldId = existing.rows[0].id;
        await client.query(
          `UPDATE moulds SET
            mould_name = COALESCE(mould_name, $1),
            customer_name = COALESCE(customer_name, $2),
            suitable_machines = COALESCE(suitable_machines, $3),
            status = 'ready'
          WHERE id = $4`,
          [m.mould_name, m.customer_name, m.suitable_machines, mouldId]
        );
      } else {
        const ins = await client.query(
          `INSERT INTO moulds (
            mould_code, mould_name, ownership, customer_name, total_cavities, active_cavities,
            yom, mould_type, gate_type, maker, suitable_machines, rack_no, status
          ) VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10, $11, 'ready')
          RETURNING id`,
          [
            m.mould_code, m.mould_name, m.ownership, m.customer_name, m.cavities,
            m.yom, m.mould_type, m.gate_type, m.tool_maker, m.suitable_machines, m.rack_no
          ]
        );
        mouldId = ins.rows[0].id;
      }

      // Link part if matching
      const partMatch = await client.query(
        'SELECT id FROM parts WHERE lower(shrp_part_code) = lower($1) OR lower(part_code) = lower($2) OR lower(customer_part_no) = lower($2) LIMIT 1',
        [m.shrp_part_name, m.part_no]
      );

      if (partMatch.rows.length > 0) {
        await client.query(
          `INSERT INTO mould_parts (mould_id, part_id, cavities_for_part)
          VALUES ($1, $2, $3)
          ON CONFLICT (mould_id, part_id) DO NOTHING`,
          [mouldId, partMatch.rows[0].id, m.cavities]
        );
      }
    }

    await client.query('COMMIT');
    console.log('Mould sync complete! Synced 69 tooling masters.');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Error syncing moulds:', err);
    throw err;
  } finally {
    client.release();
    if (closePool) {
      await pool.end();
    }
  }
}

if (require.main === module) {
  syncMoulds(true).catch(() => process.exit(1));
}

module.exports = { syncMoulds, EXCEL_MOULDS };
