const pool = require('./pool');

// High-fidelity IATF 16949 Master Moulds Definition linked to the 77 active parts
const MOULD_DEFINITIONS = [
  {
    mould_code: 'SH HC01',
    mould_name: 'A710 (A710-BBWBA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 4270,
    shots_since_pm: 4270,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['A710']
  },
  {
    mould_code: 'SH HC01A',
    mould_name: 'CEEAA-ORANGE (FC1F2CEEAA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1486,
    shots_since_pm: 1486,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE- ORANGE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['CEEAA-ORANGE']
  },
  {
    mould_code: 'SH HC02',
    mould_name: 'F364 (F364-CB5AA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04',
    linked_shrp_codes: ['F364 16C']
  },
  {
    mould_code: 'SH HC03',
    mould_name: 'F364 GS (F364-CB5AA-01-GS)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01, 02, 05',
    linked_shrp_codes: ['F364 GS']
  },
  {
    mould_code: 'SH HC04',
    mould_name: 'F442 KQ (F442-KQAAA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 675,
    shots_since_pm: 675,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02,05',
    linked_shrp_codes: ['F442 KQ']
  },
  {
    mould_code: 'SH HC05',
    mould_name: 'F442 QQ (F442-QQ7AA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 920,
    shots_since_pm: 920,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['F442 QQ']
  },
  {
    mould_code: 'SH HC06',
    mould_name: 'F442 WB (F442-WBAAA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1059,
    shots_since_pm: 1059,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['F442 WB']
  },
  {
    mould_code: 'SH HC07',
    mould_name: 'F710 (F710-AKYAA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 417,
    shots_since_pm: 417,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02,05',
    linked_shrp_codes: ['F710']
  },
  {
    mould_code: 'SH HC08',
    mould_name: 'F885 Y (F885-BB1AA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 3307,
    shots_since_pm: 3307,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02',
    linked_shrp_codes: ['F885 Y']
  },
  {
    mould_code: 'SH HC09',
    mould_name: 'AN6B (FC1F2AN6BA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 10319,
    shots_since_pm: 10319,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02,05',
    linked_shrp_codes: ['AN6B']
  },
  {
    mould_code: 'SH HC10',
    mould_name: 'AA02 Y (FC1F2SPHAA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 9550,
    shots_since_pm: 9550,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02',
    linked_shrp_codes: ['AA02 Y']
  },
  {
    mould_code: 'SH HC11',
    mould_name: 'SULLA (FC1F2SULLA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['SULLA']
  },
  {
    mould_code: 'SH HC12',
    mould_name: 'UGKCA (FC1F2UGKCA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 955,
    shots_since_pm: 955,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['UGKCA']
  },
  {
    mould_code: 'SH HC13',
    mould_name: 'UMEAB (FC1F2UMEAB01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['UMEAB']
  },
  {
    mould_code: 'SH HC14',
    mould_name: 'HA715 - W501 (HA715L5G1A01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02, 03',
    linked_shrp_codes: ['HA715 - W501']
  },
  {
    mould_code: 'SH HC15',
    mould_name: 'CXGAA (HC442CXGAA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 05',
    linked_shrp_codes: ['CXGAA']
  },
  {
    mould_code: 'SH HC16',
    mould_name: 'AA03 (HC442SPHAA03)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 5224,
    shots_since_pm: 5224,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['AA03']
  },
  {
    mould_code: 'SH HC17',
    mould_name: 'SULAC (HC442SULAC01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['SULAC']
  },
  {
    mould_code: 'SH HC18',
    mould_name: 'QQVBA W / Y (HC443QQVBA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02, VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1676,
    shots_since_pm: 1676,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02, VSIM 01',
    linked_shrp_codes: ['QQVBA W', 'QQVBA Y']
  },
  {
    mould_code: 'SH HC19',
    mould_name: 'HL180 JLR CAP (HL180F4W1A01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['HL180']
  },
  {
    mould_code: 'SH HC20',
    mould_name: 'DH7AA (HR230DH7AA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1720,
    shots_since_pm: 1720,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04',
    linked_shrp_codes: ['DH7AA']
  },
  {
    mould_code: 'SH HC21',
    mould_name: 'PDPKA (HR230PDPKA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1907,
    shots_since_pm: 1907,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04',
    linked_shrp_codes: ['PDPKA']
  },
  {
    mould_code: 'SH HC22',
    mould_name: 'VW DIA 16 - HW773A (HW773G9E1A01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 7213,
    shots_since_pm: 7213,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['VW DIA 16 - HW773A']
  },
  {
    mould_code: 'SH HC23',
    mould_name: 'VW DIA 8 - HW773B (HW773G9E1B01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 13846,
    shots_since_pm: 13846,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['VW DIA 8 - HW773B']
  },
  {
    mould_code: 'SH HC24',
    mould_name: 'NCBA (R230-NC5BA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 03, HSIM - 05',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 6370,
    shots_since_pm: 6370,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02,03,05',
    linked_shrp_codes: ['NCBA']
  },
  {
    mould_code: 'SH HC25',
    mould_name: 'NCBB (R230-NC5BB-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 5090,
    shots_since_pm: 5090,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['NCBB']
  },
  {
    mould_code: 'SH HC26',
    mould_name: '1901 (V0LC-01C019-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['1901']
  },
  {
    mould_code: 'SH HC27',
    mould_name: '2100 (V0LC-01C021-00)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 3250,
    shots_since_pm: 3250,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['2100']
  },
  {
    mould_code: 'SH HC28',
    mould_name: '2200 (V0LC-01C022-00)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01, VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 13079,
    shots_since_pm: 13079,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01, VIM 02',
    linked_shrp_codes: ['2200']
  },
  {
    mould_code: 'SH HC29',
    mould_name: '2800 (V0LC-01C028-00)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01, VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 3583,
    shots_since_pm: 3583,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01, VIM 02',
    linked_shrp_codes: ['2800']
  },
  {
    mould_code: 'SH HC30',
    mould_name: 'VPAA (VP5N1H-407721-AA)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 03, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 5242,
    shots_since_pm: 5242,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02, 03,05',
    linked_shrp_codes: ['VPAA']
  },
  {
    mould_code: 'SH HC31',
    mould_name: 'VPFA (VP5N1H-407721-FA)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02,05',
    linked_shrp_codes: ['VPFA']
  },
  {
    mould_code: 'SH HC32',
    mould_name: 'DM1C (DM1C4UBH1B01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 03, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: TPE-A85 | Suitable: HSIM 03, 05',
    linked_shrp_codes: ['DM1C', 'DM1C1QRJAA01']
  },
  {
    mould_code: 'SH HC33',
    mould_name: 'LBB (HC442L3LBB01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 4088,
    shots_since_pm: 4088,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['LBB']
  },
  {
    mould_code: 'SH HC34',
    mould_name: 'LBC (HC442L3LBC02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 2113,
    shots_since_pm: 2113,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['LBC']
  },
  {
    mould_code: 'SH HC35',
    mould_name: 'LAC BLUE / GREEN (HC442L3LAC01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 5742,
    shots_since_pm: 5742,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 03',
    linked_shrp_codes: ['LAC Blue', 'LAC Green']
  },
  {
    mould_code: 'SH HC36',
    mould_name: 'AFM BIG / CAP ASY-SUC (CA581CAWXX01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Rubber Compression Mould',
    suitable_machines: 'RUB - 01',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: CA581 BIG | Suitable: RUB-01',
    linked_shrp_codes: ['AFM BIG']
  },
  {
    mould_code: 'SH HC37',
    mould_name: 'AFM SMALL / CAP ASY-DIS (CA582DDRXX01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Rubber Compression Mould',
    suitable_machines: 'RUB - 01',
    total_cavities: 2,
    active_cavities: 2,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: CA582 SMALL | Suitable: RUB-01',
    linked_shrp_codes: ['AFM SMALL']
  },
  {
    mould_code: 'SH HC38',
    mould_name: 'OERAA (HC442OERAA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['OERAA']
  },
  {
    mould_code: 'SH HC39',
    mould_name: 'QVEAC (HC442QVEAC01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 2100,
    shots_since_pm: 2100,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['QVEAC']
  },
  {
    mould_code: 'SH HC40',
    mould_name: 'QVEBC (HC442QVEBC01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['QVEBC']
  },
  {
    mould_code: 'SH HC41',
    mould_name: 'T40 (RM-19D935-BA)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['T40']
  },
  {
    mould_code: 'SH HC42',
    mould_name: 'UMEAA (FC1F2UMEAA01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 724,
    shots_since_pm: 724,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['UMEAA']
  },
  {
    mould_code: 'SH HC43',
    mould_name: 'UMNAA (HC442UMNAA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 845,
    shots_since_pm: 845,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['UMNAA']
  },
  {
    mould_code: 'SH HC44',
    mould_name: 'NDGAA (FC1F2NDGAA02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 906,
    shots_since_pm: 906,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02',
    linked_shrp_codes: ['NDGAA']
  },
  {
    mould_code: 'SH HP01',
    mould_name: 'PUNE B (FC1E1BAE1D01)',
    ownership: 'Customer',
    customer_name: 'HASI PUNE',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI PUNE',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 03, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 6370,
    shots_since_pm: 6370,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: PPCP | Suitable: HSIM 03, 05',
    linked_shrp_codes: ['PUNE B']
  },
  {
    mould_code: 'SH HP02',
    mould_name: 'PUNE S (HR241BAE1B01)',
    ownership: 'Customer',
    customer_name: 'HASI PUNE',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI PUNE',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 03, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 6743,
    shots_since_pm: 6743,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: PPCP | Suitable: HSIM 03, 05',
    linked_shrp_codes: ['PUNE S']
  },
  {
    mould_code: 'SH HB01',
    mould_name: 'BH-DIA 16 - MAA (PL FC1E4K5MAA - 00)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 8820,
    shots_since_pm: 8820,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 05, 02',
    linked_shrp_codes: ['BH-DIA 16 - MAA']
  },
  {
    mould_code: 'SH HB02',
    mould_name: 'BH-DIA 12 -MBA (PL FC1E4K5MBA - 00)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 05, 02',
    linked_shrp_codes: ['BH-DIA 12 -MBA']
  },
  {
    mould_code: 'SH HB03',
    mould_name: 'BH-DIA 8 (FC1P4L1E1A01)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 04, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 04,05',
    linked_shrp_codes: ['BH-DIA 8']
  },
  {
    mould_code: 'SH HB04',
    mould_name: 'OUTLET / INLET (PLHC442G6C1B / PLHC442G6C1A)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM-02',
    linked_shrp_codes: ['OUTLET', 'INLET']
  },
  {
    mould_code: 'SH HB05',
    mould_name: 'HR241 (HR241G6C1A01)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 02, HSIM - 03, HSIM - 05',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 02, 03, 05',
    linked_shrp_codes: ['HR241']
  },
  {
    mould_code: 'SH HB06',
    mould_name: 'R101 (R101WC9AA01)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['R101']
  },
  {
    mould_code: 'SH HB07',
    mould_name: '9AA (VPR230WC9AA01)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['9AA']
  },
  {
    mould_code: 'SH HB08',
    mould_name: '9AB (VPR230-WC9AB-01)',
    ownership: 'Customer',
    customer_name: 'HCCSIL BHIWADI',
    tool_maker: 'HCCSIL Tooling',
    funded_by: 'HCCSIL BHIWADI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 1815,
    shots_since_pm: 1815,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['9AB']
  },
  {
    mould_code: 'SH WN01',
    mould_name: 'F390 (F390-QQDC-A02)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['F390']
  },
  {
    mould_code: 'SH WN02',
    mould_name: 'KQ NEW (F442-KQ)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['KQ NEW']
  },
  {
    mould_code: 'SH WN03',
    mould_name: 'SHRP-T7 (SHRP-T7)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['SHRP-T7']
  },
  {
    mould_code: 'SH WN04',
    mould_name: 'SHRP-T8 (SHRP-T8)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['SHRP-T8']
  },
  {
    mould_code: 'SH WN05',
    mould_name: 'DA (WC-SCP-ECC21-DA01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['DA']
  },
  {
    mould_code: 'SH WN06',
    mould_name: 'LMF (WC-SCP-ECC21-LMF01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['LMF']
  },
  {
    mould_code: 'SH WN07',
    mould_name: 'LMM (WC-SCP-eCC21-Lmm01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['LMM']
  },
  {
    mould_code: 'SH WN08',
    mould_name: 'SMF (WC-SCP-ECC21-SMF01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['SMF']
  },
  {
    mould_code: 'SH WN09',
    mould_name: 'SMM (WC-SCP-eCC21-Smm01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 03',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 03',
    linked_shrp_codes: ['SMM']
  },
  {
    mould_code: 'SH WN10',
    mould_name: 'NADB (WC-SCP-SC21NA-DB-01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 755,
    shots_since_pm: 755,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM - 02',
    linked_shrp_codes: ['NA-DB']
  },
  {
    mould_code: 'SH WN11',
    mould_name: 'NALC (WC-SCP-SC21NA-LC-01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM - 02',
    linked_shrp_codes: ['NA-LC']
  },
  {
    mould_code: 'SH WN12',
    mould_name: 'NATB (WC-SCP-SC21NA-TB-T01)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM - 02',
    linked_shrp_codes: ['NA-TB']
  },
  {
    mould_code: 'SH SC01',
    mould_name: 'VP6T (VP6TLU-11N087-AA)',
    ownership: 'Customer',
    customer_name: 'SONA COMSTAR',
    tool_maker: 'Sona Tooling',
    funded_by: 'SONA COMSTAR',
    tool_type: 'Rubber Compression Mould',
    suitable_machines: 'RUB - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: N.RUB | Suitable: RUB-01',
    linked_shrp_codes: ['VP6T']
  },
  {
    mould_code: 'SH WN13',
    mould_name: 'SHRP-T10 (SHRP-T10)',
    ownership: 'Customer',
    customer_name: 'WONJIN',
    tool_maker: 'Wonjin Tooling',
    funded_by: 'WONJIN',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VIM 02',
    linked_shrp_codes: ['SHRP-T10']
  },
  {
    mould_code: 'SH HC45',
    mould_name: 'ATBAB (F442-ATBAB02)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: HSIM 01,02',
    linked_shrp_codes: ['ATBAB']
  },
  {
    mould_code: 'SH GEN01',
    mould_name: 'SYRINGE CAP (SYRINGE CAP)',
    ownership: 'SHRP',
    customer_name: 'SHRP Internal',
    tool_maker: 'SHRP In-House',
    funded_by: 'SHRP Internal',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01, HSIM - 02',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: PP | Suitable: HSIM 01,02',
    linked_shrp_codes: ['SYRINGE CAP']
  },
  {
    mould_code: 'SH GEN02',
    mould_name: 'HandlePlastic (HandlePlastic)',
    ownership: 'SHRP',
    customer_name: 'SHRP Internal',
    tool_maker: 'SHRP In-House',
    funded_by: 'SHRP Internal',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01',
    total_cavities: 1,
    active_cavities: 1,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: PP | Suitable: HSIM 01',
    linked_shrp_codes: ['HandlePlastic']
  },
  {
    mould_code: 'SH GEN03',
    mould_name: 'VK GR -6 (VK GR -6)',
    ownership: 'SHRP',
    customer_name: 'SHRP Internal',
    tool_maker: 'SHRP In-House',
    funded_by: 'SHRP Internal',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'HSIM - 01',
    total_cavities: 1,
    active_cavities: 1,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: PP | Suitable: HSIM 01',
    linked_shrp_codes: ['VK GR -6']
  },
  {
    mould_code: 'SH OLD01',
    mould_name: 'F442 QQ - Old (F442-QQ7AA-01)',
    ownership: 'Customer',
    customer_name: 'HASI CHENNAI',
    tool_maker: 'HASI Tooling Div',
    funded_by: 'HASI CHENNAI',
    tool_type: 'Cold Runner (Two Plate)',
    suitable_machines: 'VSIM - 01',
    total_cavities: 4,
    active_cavities: 4,
    total_rated_life_shots: 500000,
    pm_interval_shots: 20000,
    cumulative_shots: 0,
    shots_since_pm: 0,
    storage_location: 'Tool Crib Rack A-01',
    status: 'ready',
    notes: 'Raw Material: LDPE | Suitable: VSIM 01',
    linked_shrp_codes: ['F442 QQ']
  }
];

async function syncMoulds(closePool = false) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Ensure table structure is updated with any missing columns
    await client.query(`
      ALTER TABLE moulds ADD COLUMN IF NOT EXISTS tool_maker TEXT;
      ALTER TABLE moulds ADD COLUMN IF NOT EXISTS funded_by TEXT;
      ALTER TABLE moulds ADD COLUMN IF NOT EXISTS tool_type TEXT DEFAULT 'Cold Runner (Two Plate)';
      ALTER TABLE moulds ADD COLUMN IF NOT EXISTS suitable_machines TEXT;
      ALTER TABLE moulds ADD COLUMN IF NOT EXISTS total_rated_life_shots INTEGER DEFAULT 500000;
    `);

    let mouldsInsertedOrUpdated = 0;
    let partsLinked = 0;

    for (const m of MOULD_DEFINITIONS) {
      // 1. Upsert mould
      const mouldRes = await client.query(`
        INSERT INTO moulds (
          mould_code, mould_name, ownership, customer_name, tool_maker, funded_by,
          tool_type, suitable_machines, total_cavities, active_cavities,
          total_rated_life_shots, pm_interval_shots, cumulative_shots, shots_since_pm,
          storage_location, status, notes
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
        ON CONFLICT (mould_code) DO UPDATE SET
          mould_name = COALESCE(moulds.mould_name, EXCLUDED.mould_name),
          ownership = COALESCE(moulds.ownership, EXCLUDED.ownership),
          customer_name = COALESCE(moulds.customer_name, EXCLUDED.customer_name),
          tool_maker = COALESCE(moulds.tool_maker, EXCLUDED.tool_maker),
          funded_by = COALESCE(moulds.funded_by, EXCLUDED.funded_by),
          tool_type = COALESCE(moulds.tool_type, EXCLUDED.tool_type),
          suitable_machines = COALESCE(moulds.suitable_machines, EXCLUDED.suitable_machines),
          total_cavities = COALESCE(moulds.total_cavities, EXCLUDED.total_cavities),
          active_cavities = COALESCE(moulds.active_cavities, EXCLUDED.active_cavities),
          total_rated_life_shots = COALESCE(moulds.total_rated_life_shots, EXCLUDED.total_rated_life_shots),
          pm_interval_shots = COALESCE(moulds.pm_interval_shots, EXCLUDED.pm_interval_shots),
          storage_location = COALESCE(moulds.storage_location, EXCLUDED.storage_location),
          notes = COALESCE(moulds.notes, EXCLUDED.notes)
        RETURNING id
      `, [
        m.mould_code,
        m.mould_name,
        m.ownership,
        m.customer_name,
        m.tool_maker || 'SHRP In-House',
        m.funded_by || (m.ownership === 'Customer' ? m.customer_name : 'SHRP Internal'),
        m.tool_type || 'Cold Runner (Two Plate)',
        m.suitable_machines || 'HSIM - 01',
        m.total_cavities || 1,
        m.active_cavities || 1,
        m.total_rated_life_shots || 500000,
        m.pm_interval_shots || 20000,
        m.cumulative_shots || 0,
        m.shots_since_pm || 0,
        m.storage_location || 'Tool Crib Rack A-01',
        m.status || 'ready',
        m.notes || ''
      ]);

      const mouldId = mouldRes.rows[0].id;
      mouldsInsertedOrUpdated++;

      // 2. Link parts in mould_parts table
      for (const shrpCode of m.linked_shrp_codes) {
        const partRes = await client.query(`
          SELECT id, cavity_count FROM parts
          WHERE (shrp_part_code = $1 OR part_code = $1 OR customer_part_no = $1)
            AND active = TRUE
          LIMIT 1
        `, [shrpCode]);

        if (partRes.rows.length > 0) {
          const partId = partRes.rows[0].id;
          const cavities = partRes.rows[0].cavity_count || m.total_cavities || 1;

          await client.query(`
            INSERT INTO mould_parts (mould_id, part_id, cavities_for_part)
            VALUES ($1, $2, $3)
            ON CONFLICT (mould_id, part_id) DO NOTHING
          `, [mouldId, partId, cavities]);

          partsLinked++;
        }
      }
    }

    await client.query('COMMIT');
    console.log(`[DB-INIT] Moulds synchronized successfully! Processed ${mouldsInsertedOrUpdated} moulds, created/verified ${partsLinked} part linkages.`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('[DB-INIT] Error syncing moulds:', err);
    throw err;
  } finally {
    client.release();
    if (closePool) {
      await pool.end();
    }
  }
}

if (require.main === module) {
  syncMoulds(true).catch(() => process.exit(1));
}

module.exports = { syncMoulds, MOULD_DEFINITIONS };
